### ISSUE TITLE
Getting the discord.py Error even though I have the requirments installed

### ISSUE THREAD

**Issue by TheBooker66** [AlexFlipnote/GiveMeBadge#104]
Basically the title.

I'm getting the `Either discord.py is not installed or you are running an older and unsupported version of it.Please make sure to check that you have the latest version of discord.py! (try reinstalling the requirements?)` error message even though when I run `pip install -r requirements.txt` (or even `python -m pip install -r requirements.txt`) I get `Requirement already satisfied` for every package.

I'm running Python 3.13.0 and I have the latest code. I've even tried to reinstall it, but that didn't solve the issue.

**Comment by AlexFlipnote** [comment]
Ah, thought I replied to this,
This error sadly only appears if it did in fact fail to import discord.py, so somewhere down the line of your command usage, it did fail to install it. There are many other commands you can possibly try, maybe even add `--upgrade` at the end to make sure it installs latest version

**Comment by TheBooker66** [comment]
I really don't know what could have went wrong. I tried reinstalling again, with new code in a new location, and with the `--upgrade` flag, but it still doesn't work. This is the message I'm getting:
```
Requirement already satisfied: discord.py in c:\users\user\appdata\roaming\python\python313\site-packages (from -r requirements.txt (line 1)) (2.4.0)
```

However, I just noticed I'm also getting this message: `Defaulting to user installation because normal site-packages is not writeable`, so might that be the problem? I'm running the `install` command from the folder in which the code is in, which is located in downloads. I've tried looking it up but didn't come up with a meaningful solution. Would appreciate help on this.

I've also tried using Pycharm - installing the reqs and running through it - but it doesn't make a difference.

**Comment by AlexFlipnote** [comment]
Not sure if it makes a difference, but attempt to install it with a command prompt running on admin mode?

**Comment by TheBooker66** [comment]
Tried it :(

**Comment by AlexFlipnote** [comment]
My other solution would then be to try venv mode
- `python -m venv .venv`
- `.\.venv\Scripts\activate.bat`
- `pip install -r requirements.txt`
- `python index.py`
🔗 https://docs.python.org/3/library/venv.html

At least then you are more sure that the Python is local as well, just in case there are some weird scenario with folder permissions that you mentioned earlier. Just to make sure as well, I reinstalled everything on my local instance, code works so.. I would definetly try venv and see if there are any noticable difference

**Comment by TheBooker66** [comment]
Tried it, got the same error with discord.py and the same `Defaulting to user installation because normal site-packages is not writeable` message. I tried a few other locations in my pc, all of them accessible to a normal user, to no avail.

I tried using the `--target` option and installing to the project folder. That didn't work either.
However, I did notice something: when I tried this, I got exception when running `index.py`, saying that `requests` wasn't installed. I hadn't gotten that error before, meaning `requests`, and so probably `discord.py` as well, were installed and working when I first tried to run the code. However, it still doesn't work. Any thoughts?

**Comment by AlexFlipnote** [comment]
bit of a confusing error, because the requirements does have that package as a thing you will install 
https://github.com/AlexFlipnote/GiveMeBadge/blob/master/requirements.txt#L2

**Comment by TheBooker66** [comment]
Yeah, I noticed that and that's why I was confused: `discord.py` was throwing the error a long time before `requests` was, even though they should both behave the same and `requstes` should throw an error first.

I might try running the script on a different machine later.

**Comment by TheBooker66** [comment]
After a few days of being too busy for this, I managed to work around the issue using Google Colab.
I took your `index.py` and added these lines to the top of it:
```python
%pip install discord.py requests colorama==0.4.6 nest_asyncio

import nest_asyncio
nest_asyncio.apply()
```

The first one tells google to install the required packages (see [here](https://stackoverflow.com/a/61212861/17396626)), and the second and third allow the final line (`client.run(token)`) to be run, because of constraints with how google colab works (see [here](https://stackoverflow.com/a/63539722/17396626)).

Even though I didn't manage to run to it locally, it ran alright after only ten minutes of tinkering and the bot replied to me. Happy with the result. Thanks for the help, and sorry for the trouble.

As a side note, it's kind of funny how I use to bot to get the developer badge without developing anything, but I just did some developent.

**Comment by rawpie2** [comment]
how do i apply this fix because i have the same issue

**Comment by TheBooker66** [comment]
Like I wrote in my previous comment: Create a Google Colab notebook, copy `index.py` to it and add the code mentioned to the top of the notebook.

**Comment by miuku** [comment]
`pip install audioop-lts` fixed it for me
