### ISSUE TITLE
Error on Linux.

### ISSUE THREAD

**Issue by levithebevi** [AlexFlipnote/GiveMeBadge#11]
![image](https://user-images.githubusercontent.com/108506153/201491673-b26606fc-b385-486f-8276-57a4d3de6fbd.png)
I get this error when trying to put the discord token in.

**Comment by AlexFlipnote** [comment]
I tested it on my Debian server and it works fine 🤔 
Also I recommend resetting your token since you leaked it.
![image](https://user-images.githubusercontent.com/19587382/201491811-f826804f-35c6-4317-a01b-ab1ba73f1dcb.png)

**Comment by SlimeGuyy** [comment]
This happened to me too but im on a Mac (I am to lazy to blur it so I reseted my token after)
<img width="1161" alt="Screen Shot 2022-11-12 at 3 07 28 PM" src="https://user-images.githubusercontent.com/89882214/201492578-0936f859-359c-4c0f-9e10-980b879c8a63.png">

**Comment by AlexFlipnote** [comment]
Are you using the mac version?

**Comment by levithebevi** [comment]
> I tested it on my Debian server and it works fine thinking Also I recommend resetting your token since you leaked it. ![image](https://user-images.githubusercontent.com/19587382/201491811-f826804f-35c6-4317-a01b-ab1ba73f1dcb.png)

Thanks for the tip, coincidentally I had already reset it while trying to fix it. I'm gonna try compiling and I'll update you if it fixes anything.

**Comment by AlexFlipnote** [comment]
Sure thing, if anything, could you tell which Python version you used to compile if it works?

**Comment by levithebevi** [comment]
> Sure thing, if anything, could you tell which Python version you used to compile if it works?

Got this error while compiling on Python 3.10.8, will try to compile on an earlier version now.
![image](https://user-images.githubusercontent.com/108506153/201494083-81030e45-a7e4-4695-9a69-f90426c01f39.png)

**Comment by AlexFlipnote** [comment]
You have to install the requirements

**Comment by levithebevi** [comment]
> You have to install the requirements

Python 3.10 > Python 3.6
Will try to compile on Python 3.6 in a moment.

**Comment by AlexFlipnote** [comment]
`pip install -r requirements.txt`

**Comment by levithebevi** [comment]
> `pip install -r requirements.txt`

Oh my god, how did I not see this? Thank you.
