### ISSUE TITLE
not compatible for 86x OS...

### ISSUE THREAD

**Issue by iahmtb** [AlexFlipnote/GiveMeBadge#18]
when I open the GiveMeBadge.exe, it says it is not compatible with my pc. I even tried the GiveMeBadge_1.0.3-win32.exe it didn't work too.

**Comment by AlexFlipnote** [comment]
If you have a Mac, you need to use the macoss.app version of it, unzip the application and run it.
![image](https://user-images.githubusercontent.com/19587382/201523662-2ba5ef80-c54a-4399-8a17-e30ce5429eeb.png)

**Comment by iahmtb** [comment]
I'm in a windows desktop
