### ISSUE TITLE
not a real issue but you need to sign the file

### ISSUE THREAD

**Issue by mohsenemx** [AlexFlipnote/GiveMeBadge#2]
you know windows is dumb af and will sometimes remove the file cuz it think oh "this file is infected" or something.
+ you'll need to keep the app updated cuz discord is dumb af too and will make it "not work"

**Comment by Wolfhound905** [comment]
> you need to sign the file

This is expensive for an open-source project with no sponsors.
Also, there is really no need.

**Comment by AlexFlipnote** [comment]
I would gladly pay for it if it wasn't expensive, thing is too is that you have to pay for it yearly, so I don't see it worth it.. Regardless, thank you for being cautious <3
