### ISSUE TITLE
Error on iMac Build

### ISSUE THREAD

**Issue by Dell-Optiplex-390** [AlexFlipnote/GiveMeBadge#21]
![Untitled](https://user-images.githubusercontent.com/80816207/201536744-9e1624f5-1c60-46b1-bbb7-9320c33b0958.jpeg)

**Comment by armfuldev** [comment]
<img width="998" alt="Screen Shot 2022-11-13 at 19 06 52" src="https://user-images.githubusercontent.com/55296171/201537259-20c7748b-d744-468c-8477-c1985d143641.png">

**Comment by Dell-Optiplex-390** [comment]
It's giving me an error instead, and sorry for the multiple posts on the server, it said it was erroring but it wasn't and instead was creating a post

**Comment by AlexFlipnote** [comment]
Try the mobile method instead if you can't get the MacOS one working, I only support latest MacOS since I am unable to debug lower versions myself sadly.

**Comment by Dell-Optiplex-390** [comment]
I did the mobile method already but it's been 24 hours but it hasn't approved on the developer portal
