### ISSUE TITLE
Add AUR package

### ISSUE THREAD

**Issue by dumbasPL** [AlexFlipnote/GiveMeBadge#23]
This is a note to myself to add this to the [Arch User Repository](https://aur.archlinux.org/) later.

If you want to be the maintainer of the aur package as well let me know

**Comment by AlexFlipnote** [comment]
very nice reminder yes yes

**Comment by dumbasPL** [comment]
> very nice reminder yes yes

Thanks for the ping :sweat_smile:, will do it today.

For context, I'm used to issues sitting open for months, It's a reminder in a way that it will sit on my https://github.com/issues list.

**Comment by dumbasPL** [comment]
Done. Standard, vcs and binary variants available

https://aur.archlinux.org/packages/givemebadge
https://aur.archlinux.org/packages/givemebadge-git
https://aur.archlinux.org/packages/givemebadge-bin

**Comment by dumbasPL** [comment]
Also, you can add Arch linux to the `Confirmed to work with` section
