### ISSUE TITLE
getting [88010] Failed to execute script 'index' due to unhandled exception! on macOS Ventura

### ISSUE THREAD

**Issue by un-creative** [AlexFlipnote/GiveMeBadge#31]

**Comment by sourcelocation** [comment]
Same issue

**Comment by sourcelocation** [comment]
Fixed the issue by downloading source code and running `cd /path/to/source/code`, `pip3 install -r requirements.txt`, `python3 index.py`

**Comment by AlexFlipnote** [comment]
For some reason the MacOS software can be somtimes hit and miss.

**Comment by MaterArc** [comment]
please fix this

**Comment by AlexFlipnote** [comment]
So far I have no idea how to fix it, it is being compiled using a macos docker container provided by GitHub Actions, if that does not work, use source-code instead. (By installing Python and running from that)
