### ISSUE TITLE
Suggestion : Put comments to help people learn python (also to help discord have mor developer)

### ISSUE THREAD

**Issue by scratchusernamemrtbts** [AlexFlipnote/GiveMeBadge#35]
So basically as discord has stated they want the developer badge thing to try and get people to learn how to code
so here's my idea on how you can help with that
to the 1% of people who actually opened the python file and read it
you might be able to help them learn python by putting comments explaining what each lines does

(also ignore my cringe username that was so long ago)

**Comment by AlexFlipnote** [comment]
Sure, I can look in to making it more user-friendly with comments!

**Comment by AlexFlipnote** [comment]
Added a few comments here and there now
