### ISSUE TITLE
ModuleNotFoundError: No module named 'requests'

### ISSUE THREAD

**Issue by deceased1** [AlexFlipnote/GiveMeBadge#39]
I've installed the updated `requirements.txt` and I have run the command `pip install requests` and I am still met with this Module Error:

ModuleNotFoundError: No module named 'requests'

**Comment by AlexFlipnote** [comment]
Then do `python -m pip install -r requirements.txt`

**Comment by deceased1** [comment]
> Then do `python -m pip install -r requirements.txt`

I've done that and yet again when trying to run `index.py` the same area is there.

**Comment by kinggames12** [comment]
i can`t show this app

**Comment by deceased1** [comment]
> i can`t show this app

what?

**Comment by AlexFlipnote** [comment]
> > Then do `python -m pip install -r requirements.txt`
> 
> I've done that and yet again when trying to run `index.py` the same error is there.

Then the pip/python you are using to install is different from what you are executing with python. Try reinstalling and see if it works.
