### ISSUE TITLE
ImportError: cannot import name 'app_commands'

### ISSUE THREAD

**Issue by LordCrazyOfLife** [AlexFlipnote/GiveMeBadge#41]
cant open the app even though i copied everything to the letter

**Comment by LordCrazyOfLife** [comment]
C:\Users\Administrator\Desktop\GiveMeBadge-master>python index.py
Traceback (most recent call last):
  File "index.py", line 3, in <module>
    from discord import app_commands, Intents, Client, Interaction
ImportError: cannot import name 'app_commands'

C:\Users\Administrator\Desktop\GiveMeBadge-master>

this is the full error

**Comment by AlexFlipnote** [comment]
Install discord.py latest
