### ISSUE TITLE
Invalid Syntax in index.py

### ISSUE THREAD

**Issue by AdvitSingh5** [AlexFlipnote/GiveMeBadge#42]
![image](https://user-images.githubusercontent.com/115704398/204258952-508214d7-d2b8-4eb0-9b53-f518a406d698.png)
Is this only for me? if yes then can anyoen tell how to resolve this. pls help.

**Comment by AlexFlipnote** [comment]
Update your Python version

**Comment by AdvitSingh5** [comment]
ok thanks i got it.
