### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by ersu98** [AlexFlipnote/GiveMeBadge#46]
From the official discord developer server. (Source: [Discord](https://discord.gg/discord-developers/)) You should add this to README.md. 
Some people may not find the issue to why they dont get the badge after 24hrs.

![image](https://user-images.githubusercontent.com/18552828/205516086-1ebbf0cf-3122-4f4f-9a97-23571053e87d.png)

**Comment by AlexFlipnote** [comment]
Don't think it is needed..
