### ISSUE TITLE
Remove the Exe from source code *

### ISSUE THREAD

**Issue by cyberofficial** [AlexFlipnote/GiveMeBadge#5]
You should remove the exe from the source code and should be placed into releases: https://github.com/AlexFlipnote/GiveMeBadge/releases 

GitHub doesn't like when people put finished binaries in their source code unless needed to.
They have different servers based on code and releases. Releases are more better off with hosted content not the source tree it self.

Your file can be rated limited when downloaded too much which can lock out your repo.

**Comment by AlexFlipnote** [comment]
Ah sure, I will look in to moving it and adding a README instead saying that it has been moved to releases instead. Will update when that happens.

**Comment by AlexFlipnote** [comment]
Done, it has now been moved.
