### ISSUE TITLE
Pls help.

### ISSUE THREAD

**Issue by Ynosamo** [AlexFlipnote/GiveMeBadge#53]
C:\Users\Admin\AppData\Local\Programs\Python\Python35\python.exe
C:\Users\Admin\AppData\Local\Microsoft\WindowsApps\python.exe
C:\Users\Admin\AppData\Local\Programs\Python\Python311\python.exe
  File "index.py", line 41
    "Authorization": f"Bot {token}"
                                  ^
SyntaxError: invalid syntax

**Comment by Ynosamo** [comment]
![image](https://user-images.githubusercontent.com/82882527/207860242-89779ec0-b1e6-42ad-bb88-57e332fb9e85.png)

**Comment by AlexFlipnote** [comment]
You are running on Python 2, use Python 3.7 or higher 

![image](https://user-images.githubusercontent.com/19587382/207860572-d58dce48-7ec2-413d-bc03-2a9e6903a0b9.png)

**Comment by Ynosamo** [comment]
thanx
