### ISSUE TITLE
Removal of Releases and Packages section

### ISSUE THREAD

**Issue by ZackeryRSmith** [AlexFlipnote/GiveMeBadge#56]
I think these should be disabled if they aren't going to be used.
![image](https://user-images.githubusercontent.com/72983221/208030298-546d8cfd-83b7-4d41-a1e9-aaa50666f46d.png)

**Comment by AlexFlipnote** [comment]
I can't seem to find a way to hide it, unless I am blind and my Google skills are shit lmao. Visited another repository I own as well where I have never used the releases and it is there too. If you got some instructions on how to do it, please let me know :heart:

**Comment by vitalkanev** [comment]
> I can't seem to find a way to hide it, unless I am blind and my Google skills are shit lmao. Visited another repository I own as well where I have never used the releases and it is there too. If you got some instructions on how to do it, please let me know ❤️

It *is* possible to hide these sections. Just click the :gear: icon on the right side of the repository and untick these options:

![image](https://user-images.githubusercontent.com/18398761/208109679-ab246df0-e41b-44f9-806a-2e3e04a2d14d.png)

**Comment by ZackeryRSmith** [comment]
![image](https://user-images.githubusercontent.com/72983221/208110158-373837bd-e8fc-4fd3-ba73-a28f77fe339a.png)

**Comment by AlexFlipnote** [comment]
Oh, *theeere* it is.. I was in the general settings for this repository, looking all around. Fixed now!
