### ISSUE TITLE
Consider disabling Github actions

### ISSUE THREAD

**Issue by ZackeryRSmith** [AlexFlipnote/GiveMeBadge#64]
As everything is self ran now, there is no reason to have Github actions. Which previously did automatic releases. This isn't functionally any different but does make the project page a bit cleaner.
![image](https://user-images.githubusercontent.com/72983221/210184192-508d2188-0c7b-4f73-999d-e1e3c86652ed.png)

**Comment by AlexFlipnote** [comment]
I actually plan to make a website (something like https://givemebadge.alexflipnote.dev and host it on GitHub. We will see.

**Comment by ZackeryRSmith** [comment]
> I actually plan to make a website (something like https://givemebadge.alexflipnote.dev) and host it on GitHub. We will see.

I'll mess around with the idea of creating a website, seems like a fun way to blow some time.
