### ISSUE TITLE
D: i have a problem

### ISSUE THREAD

**Issue by dearep** [AlexFlipnote/GiveMeBadge#66]
C:\Users\lu

**Comment by ZackeryRSmith** [comment]
Please describe the issue you are facing, otherwise we can't help :/

**Comment by ZackeryRSmith** [comment]
Why did you edit your message? Your original one was just fine, either way your issue is you need to install the requests module. Please make sure to install all requirements in the `requirements.txt` file

**Comment by AlexFlipnote** [comment]
Nice edit... anyways just download requirements and maybe read the README file?
![image](https://user-images.githubusercontent.com/19587382/210263393-4f587384-d6d0-4780-bb12-4a2e1155d56b.png)
