### ISSUE TITLE
Only /hello as command

### ISSUE THREAD

**Issue by sharete** [AlexFlipnote/GiveMeBadge#82]
Everything worked until the command. When I type "/" it does not come "givemebadge" but only "hello". When I type "/hello", the links also come, as seen in the video. However, I do not get the status that I have collected the badge, but it is still output that I am not authorized.

**Comment by AlexFlipnote** [comment]
huh?

**Comment by sharete** [comment]
As you can see in the tutorial video, when you start the bot over the terminal, you can write /givemebadge in you discord server as an command in chat. But when my bot is running, I can use only /hello instead of /givemebadge. Anyway when I trigger /hello the same messages arrive in the chat window as you can see in the tutorial video when your using /givemebadge. But when Im clicking the link https://discord.com/developers/active-developer there is still the message "You are not eligible for the Active Developer Badge".

**Comment by AlexFlipnote** [comment]
Fair enolugh, I need to fix my video to only show /hello then, but that one you have to ask in https://discord.gg/discord-developers as the script is made to do the job, however if the Discord system says otherwise, that is sadly out of my control.

**Comment by sharete** [comment]
Well than I don't get this. I thought I just need to follow the introductions an than I can claim it. I made everything as me told in the video.

Thanks anyway for your effort!
