### ISSUE TITLE
Text overlaps other text

### ISSUE THREAD

**Issue by KeithBrown39423** [AlexFlipnote/GiveMeBadge#92]
![image](https://github.com/AlexFlipnote/GiveMeBadge/assets/74946768/96bc494a-f7ad-4f16-8db5-d038ceb4fc9a)

On the [docs.html](https://givemebadge.alexflipnote.dev/doc.html) page, some of the paragraphs overlap each other.

Display Resolution:
1366x768

**Comment by AlexFlipnote** [comment]
Ah, I love that resolution, reminds me of my old laptop 🙃 
Anyways yeah, I will get to this when I have time, thank you for reporting this!
Will keep you posted ❤️

**Comment by KeithBrown39423** [comment]
If I get the chance, I'll see if I can fix it, but last time I tried to fix something, it broke a bunch of other stuff so...

**Comment by AlexFlipnote** [comment]
> If I get the chance, I'll see if I can fix it, but last time I tried to fix something, it broke a bunch of other stuff so...

You can always try if you want to, however I will look into this when I can for sure. Just busy with work and stuff sadly, so that is why I have been unable to right now.

**Comment by AlexFlipnote** [comment]
Pushed a fix, should be better but not perfect, will look to better alternatives later :)

**Comment by ZackeryRSmith** [comment]
Ooopsies, my bad. When creating the website I ignorantly forgot to try other screen sizes...
