### ISSUE TITLE
I get this error at python index.py

### ISSUE THREAD

**Issue by MauroDeSmet** [AlexFlipnote/GiveMeBadge#94]
line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**Comment by MauroDeSmet** [comment]
pip install request
fixed this

**Comment by AlexFlipnote** [comment]
![image](https://github.com/AlexFlipnote/GiveMeBadge/assets/19587382/14b1fb98-3223-44ef-b9da-503c4a744450)

**Comment by MauroDeSmet** [comment]
it exists i tried pip list and it shows requests v2.31.0

**Comment by MauroDeSmet** [comment]
I did this


> ![image](https://user-images.githubusercontent.com/19587382/255385978-14b1fb98-3223-44ef-b9da-503c4a744450.png)

**Comment by AlexFlipnote** [comment]
Then you should be good

**Comment by MauroDeSmet** [comment]
Nope

**Comment by MauroDeSmet** [comment]
Requirement already satisfied: certifi>=2017.4.17 in c:\users\mauro\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from requests->-r requirements.txt (line 2)) (2023.7.22)
Requirement already satisfied: attrs>=17.3.0 in c:\users\mauro\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from aiohttp<4,>=3.7.4->discord.py->-r requirements.txt (line 1)) (23.1.0)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\mauro\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from aiohttp<4,>=3.7.4->discord.py->-r requirements.txt (line 1)) (6.0.4)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in c:\users\mauro\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from aiohttp<4,>=3.7.4->discord.py->-r requirements.txt (line 1)) (4.0.2)
Requirement already satisfied: yarl<2.0,>=1.0 in c:\users\mauro\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from aiohttp<4,>=3.7.4->discord.py->-r requirements.txt (line 1)) (1.9.2)
Requirement already satisfied: frozenlist>=1.1.1 in c:\users\mauro\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from aiohttp<4,>=3.7.4->discord.py->-r requirements.txt (line 1)) (1.4.0)
Requirement already satisfied: aiosignal>=1.1.2 in c:\users\mauro\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from aiohttp<4,>=3.7.4->discord.py->-r requirements.txt (line 1)) (1.3.1)

C:\Users\Mauro\Downloads\GiveMeBadge-master\GiveMeBadge-master>python index.py
Traceback (most recent call last):
  File "C:\Users\Mauro\Downloads\GiveMeBadge-master\GiveMeBadge-master\index.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

C:\Users\Mauro\Downloads\GiveMeBadge-master\GiveMeBadge-master>

**Comment by Qwinth** [comment]
Try python -m pip install -r requirements.txt

**Comment by MauroDeSmet** [comment]
THANKS IT WORKED

**Comment by sjello** [comment]
Hi! i been getting the same herror. i was able to run

**Comment by sjello** [comment]
Hi. i been getting the same error. 
i was able to run **python -m pip install -r requirements.txt** after that i type **cls** like it says in the video but when i go type **py index.py** i says that there is no module with the name requests.. any idea what im doing wrong?
![image](https://github.com/AlexFlipnote/GiveMeBadge/assets/134638536/2f7355c0-ba5e-4623-bbd9-f62704324cba)

**Comment by MauroDeSmet** [comment]
It works for me maybe you have python2 and python3 try deleting python2 check if it is installed pip2 --version 'pip2' is not recognized as an internal or external command,
operable program or batch file. if it says this you should be fine

**Comment by AlexFlipnote** [comment]
Closing since user has redirected their attention to #95 and original question was resolved
