### ISSUE TITLE
index.py error

### ISSUE THREAD

**Issue by sjello** [AlexFlipnote/GiveMeBadge#95]
Hi. i been getting the same error. 
i was able to run **python -m pip install -r requirements.txt** after that i type **cls** like it says in the video but when i go type **py index.py** i says that there is no module with the name requests.. any idea what im doing wrong?
![image](https://github.com/AlexFlipnote/GiveMeBadge/assets/134638536/2f7355c0-ba5e-4623-bbd9-f62704324cba)

**Comment by AlexFlipnote** [comment]
It seems like you are running `py` instead of `python` which you used to install the requirements.
- Use `python index.py` instead
- Use `py -m pip install -r requirements.txt`

**Comment by Qwinth** [comment]
Compare Python and pip versions.
`python --version`
`py --version`
`pip --version`
