### ISSUE TITLE
The application did not respond

### ISSUE THREAD

**Issue by OmaRSallaKH** [AlexFlipnote/GiveMeBadge#96]
Hello, I followed instructions carefully however I faced a problem while trying the command /hello, whenever I type "/hello" it tells me "The application did not respond" any ideas?

**Comment by AlexFlipnote** [comment]
Did you keep the command prompt open while doing the command?

**Comment by OmaRSallaKH** [comment]
Yes.

**Comment by OmaRSallaKH** [comment]
Edit: I just did what I did yesterday and everything worked just fine, sorry for the inconvenience.
